name: Continuous Integration

# This workflow runs on pushes to any branch EXCEPT main,
# and on any pull request to the main branch.
on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: A simple test step
      - name: Say hello
        run: echo "Hello, World! The CI pipeline is running."

      # We will add steps for linting, testing, and building here in future labs.

      # Step to build the Docker image
      - name: Build Docker image
        run: docker build -t hello-world-app:latest .

      # Step to scan the image for vulnerabilities with Trivy
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'hello-world-app:latest'
          format: 'table'
          exit-code: '1' # Fail the build if vulnerabilities are found
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'