name: Continuous Integration

# This workflow runs on pushes to any branch EXCEPT main,
# and on any pull request to the main branch.
on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: A simple test step
      - name: Say hello
        run: echo "Hello, World! The CI pipeline is running."

      # We will add steps for linting, testing, and building here in future labs.